# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-22 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('content_type', models.PositiveSmallIntegerField(choices=[(0, 'Text'), (1, 'Link'), (2, 'HTML'), (3, 'Image')], default=0)),
                ('data', models.BinaryField(blank=True, null=True)),
            ],
        ),
    ]
