# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-22 12:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'Launched'), (1, 'Accepted'), (2, 'Rejected'), (3, 'Finished')], default=0)),
                ('result', models.CharField(blank=True, max_length=50, null=True)),
                ('challenged', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='challenges_received', to=settings.AUTH_USER_MODEL)),
                ('challenger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='challenges_launched', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='challenge',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='challenge.Game'),
        ),
    ]
