# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-21 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_qr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='content_object_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='content_object_field_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
