# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-22 09:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_qr', '0003_action_affects'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='action',
            name='affects',
        ),
        migrations.RemoveField(
            model_name='qr',
            name='max_number_uses',
        ),
        migrations.RemoveField(
            model_name='qr',
            name='max_number_uses_per_user',
        ),
        migrations.AddField(
            model_name='action',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='action',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='max_global_uses',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='action',
            name='max_personal_uses',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='action',
            name='priority',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='action',
            name='stop',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qr',
            name='creation_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='qr',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='qr',
            name='reference',
            field=models.CharField(default='TEST', max_length=50),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='qr',
            index=models.Index(fields=['reference'], name='django_qr_q_referen_6a3683_idx'),
        ),
        migrations.AddIndex(
            model_name='qr',
            index=models.Index(fields=['enabled'], name='django_qr_q_enabled_ac9053_idx'),
        ),
        migrations.AddField(
            model_name='useraction',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_qr.Action'),
        ),
        migrations.AddField(
            model_name='useraction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
